#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    
    #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
    using CurrencySettings = CMS.PagesSettings.Forms.CurrencySettings;
    
    #line default
    #line hidden
    using DB.Entities;
    using Libs;
    
    #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_Currency.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_Currency_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_Currency_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
  
    var fieldSettings = (CurrencySettings)WebContext.FieldSettings;
	Debug.Assert(fieldSettings != null);
    var text = ViewData.TemplateInfo.FormattedModelValue.ToString();
    if (!string.IsNullOrEmpty(text))
    {
        var value = 0m;
        decimal.TryParse(text, out value);
        text = value.ToString("#,#.00");
    }
    var aSep = CultureInfo.CurrentCulture.NumberFormat.CurrencyGroupSeparator;
    var dec = CultureInfo.CurrentCulture.NumberFormat.CurrencyDecimalSeparator;

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" data-a-sep=\"");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
              Write(aSep);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-a-dec=\"");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                 Write(dec);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-alt-dec=\".\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 725), Tuple.Create("\"", 770)
            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
, Tuple.Create(Tuple.Create("", 732), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 732), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 771), Tuple.Create("\"", 784)
            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                               , Tuple.Create(Tuple.Create("", 779), Tuple.Create<System.Object, System.Int32>(text
            
            #line default
            #line hidden
, 779), false)
);

WriteLiteral(" class=\"ozi-currency\"");

WriteLiteral(" ");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                                                                                                                                           if(fieldSettings.Disabled) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("disabled=\"disabled\"");

WriteLiteral(" ");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                                                                                                                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                                                                                                                                                                                                            if(fieldSettings.Readonly) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("readonly=\"readonly\"");

WriteLiteral(" ");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Currency.cshtml"
                                                                                                                                                                                                                                                                                          }
            
            #line default
            #line hidden
WriteLiteral(" />\r\n");

        }
    }
}
#pragma warning restore 1591
