#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Checkbox.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Checkbox.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_Checkbox.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_Checkbox_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_Checkbox_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Checkbox.cshtml"
  
    var fieldSettings = WebContext.FieldSettings;
    var htmlAttrs = new Dictionary<string, object> { { "class","ozi-checkbox" } };
	Debug.Assert(fieldSettings != null);
	if(fieldSettings.Disabled)
    {
        htmlAttrs.Add("disabled","disabled");
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Checkbox.cshtml"
Write(Html.CheckBox("", (bool)(ViewData.Model != null && Boolean.Parse(ViewData.TemplateInfo.FormattedModelValue.ToString())), htmlAttrs));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
