#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_String.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_String_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_String_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
  
    var value = ViewData.TemplateInfo.FormattedModelValue;
    if (WebContext.FieldSettings.Localizable && Model != null)
    {
        value = Lp.GetMessage((Guid)Model);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 226), Tuple.Create("\"", 271)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
, Tuple.Create(Tuple.Create("", 233), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 233), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 272), Tuple.Create("\"", 286)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
, Tuple.Create(Tuple.Create("", 280), Tuple.Create<System.Object, System.Int32>(value
            
            #line default
            #line hidden
, 280), false)
);

WriteLiteral(" class=\"ozi-string\"");

WriteLiteral(" ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
                                                                                                    if (WebContext.FieldSettings.Disabled) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("disabled=\"disabled\"");

WriteLiteral(" ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
                                                                                                                                                                              }
            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
                                                                                                                                                                                 if (WebContext.FieldSettings.Readonly) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("readonly=\"readonly\"");

WriteLiteral(" ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_String.cshtml"
                                                                                                                                                                                                                                                           }
            
            #line default
            #line hidden
WriteLiteral("/>\r\n");

        }
    }
}
#pragma warning restore 1591
