#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
    using CMS.PagesSettings.Forms;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_Textarea.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_Textarea_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_Textarea_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
  
    var value = ViewData.TemplateInfo.FormattedModelValue;
    var field = (TextareaSettings)WebContext.FieldSettings;

            
            #line default
            #line hidden
WriteLiteral("\r\n<textarea");

WriteAttribute("name", Tuple.Create(" name=\"", 187), Tuple.Create("\"", 232)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 194), false)
);

WriteLiteral(" \r\n    ");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
     if(field.Disabled) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("disabled=\"disabled\"");

WriteLiteral(" ");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
                                                           } 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
     if (field.Readonly) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("readonly=\"readonly\"");

WriteLiteral(" ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
                                                            }  

            
            #line default
            #line hidden
WriteLiteral("          class=\"ozi-textarea\" \r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
     if (field.Rows != 0)
    {
            
            #line default
            #line hidden
WriteLiteral(" rows=\"");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
             Write(field.Rows);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
                                      } else {
            
            #line default
            #line hidden
WriteLiteral(" rows=\"10\" ");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Textarea.cshtml"
                                                                   Write(value);

            
            #line default
            #line hidden
WriteLiteral("</textarea>");

        }
    }
}
#pragma warning restore 1591
