#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
    using CMS.PagesSettings.Forms;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    
    #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
    using DB.Entities;
    
    #line default
    #line hidden
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_File.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_File_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {

#line 75 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
public System.Web.WebPages.HelperResult RenderScript(UploadFileSettings upload, IFileEntity file)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 76 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
 
//


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, "\r\n        files[\"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
WriteTo(__razor_helper_writer, upload.Name);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "_array\"].files.push(new FileItem({ Id: ");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                      WriteTo(__razor_helper_writer, file.Id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", Url: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                       WriteTo(__razor_helper_writer, Url.Content(file.Name));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", SourceName: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                               WriteTo(__razor_helper_writer, file.SourceName);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", Alt: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                        WriteTo(__razor_helper_writer, file.Alt);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", Title: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                            WriteTo(__razor_helper_writer, file.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", Description: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                        WriteTo(__razor_helper_writer, file.Description);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", Date: \"");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                   WriteTo(__razor_helper_writer, file.Date);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", Visibility: ");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                                            WriteTo(__razor_helper_writer, file.Visibility.ToString().ToLower());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ", IsMarked: ");


#line 79 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                                                                                             WriteTo(__razor_helper_writer, file.IsMarked.ToString().ToLower());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " }));\r\n    ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 81 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"


#line default
#line hidden
});

#line 81 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
}
#line default
#line hidden

        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_File_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
  
    var field = (UploadFileSettings)WebContext.FieldSettings;
    //var propertyValue = TypeHelpers.GetPropertyValue(Model, fieldSettings.Name);
    var propertyValue = Model;
    var isCreate = WebContext.IsCreate;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
 if (WebContext.Model == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        Необходимо сначала сохранить объект\r\n    </div> \r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 432), Tuple.Create("\"", 481)
            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
, Tuple.Create(Tuple.Create("", 437), Tuple.Create<System.Object, System.Int32>(field.GetFullPropertyId()
            
            #line default
            #line hidden
, 437), false)
, Tuple.Create(Tuple.Create("", 465), Tuple.Create("-files-container", 465), true)
);

WriteLiteral(">\r\n        <ul");

WriteAttribute("id", Tuple.Create(" id=\"", 496), Tuple.Create("\"", 534)
            
            #line 20 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
, Tuple.Create(Tuple.Create("", 501), Tuple.Create<System.Object, System.Int32>(field.GetFullPropertyId()
            
            #line default
            #line hidden
, 501), false)
, Tuple.Create(Tuple.Create("", 529), Tuple.Create("-list", 529), true)
);

WriteLiteral(" data-bind=\"sortable: { data: files, afterMove: saveList }\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"file-list-item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"fl\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                     if (field.IsImage)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <img");

WriteLiteral(" data-bind=\"attr: { src: Url }\"");

WriteLiteral(" ");

            
            #line 25 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                       Write(ByCondition(field.Size != 0, string.Format("width=\"{0}\"", field.Size)));

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");

            
            #line 26 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" data-bind=\"{attr: {href: Url}, text: SourceName}\"");

WriteLiteral("></a>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n                <div");

WriteLiteral(" class=\"fl\"");

WriteLiteral(">\r\n\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                     if (field.IsImage)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><label>Альтернативный текст</label><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value: Alt\"");

WriteLiteral(" /></div>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><label>Фото для анимационного аватара</label><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: IsMarked\"");

WriteLiteral(" /></div>\r\n\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                     if (field.ShowTitle) {
            
            #line default
            #line hidden
WriteLiteral(" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><label>Подпись</label><textarea");

WriteLiteral(" rows=\"5\"");

WriteLiteral(" style=\"width: 90%;\"");

WriteLiteral(" data-bind=\"value: Title\"");

WriteLiteral("></textarea></div> ");

            
            #line 40 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                     }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                     if (field.ShowDescription) {
            
            #line default
            #line hidden
WriteLiteral(" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><label>Описание</label><textarea");

WriteLiteral(" rows=\"5\"");

WriteLiteral(" style=\"width: 90%;\"");

WriteLiteral(" data-bind=\"value: Description\"");

WriteLiteral("></textarea></div> ");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                  }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 42 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                     if (field.Visibility) {
            
            #line default
            #line hidden
WriteLiteral(" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><label>Видимый</label><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: Visibility\"");

WriteLiteral("/></div> ");

            
            #line 42 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                   }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral("><button");

WriteLiteral(" class=\"delete\"");

WriteLiteral(">удалить</button></div>\r\n                </div>        \r\n\r\n                    \r\n" +
"\r\n            </li>\r\n        </ul>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"upload-panel\"");

WriteLiteral(" data-single=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                      Write(Html.Raw(propertyValue is IEnumerable ? "false" : "true"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-url=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                            Write(Url.Action(Actions.UploadFile));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-save-url=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                            Write(Url.Action(Actions.SaveFileData));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-delete-url=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                                Write(Url.Action(Actions.DeleteFile));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-name=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                                                                            Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-id=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                                                                                                                                                                 Write(WebContext.Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n");

            
            #line 52 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n\r\n        files[\"");

            
            #line 55 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
           Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("_array\"] = { files: ko.observableArray([]), saveList: function() {\r\n            s" +
"aveOrder(\"");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                   Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("_array\", \"");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                         Write(Url.Action(Actions.SaveOrder));

            
            #line default
            #line hidden
WriteLiteral("\", ");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                            Write(WebContext.Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", \"");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                     Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("\", \"");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                                                                                                     Write(field.Name);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n        }};\r\n\r\n");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
         if (propertyValue is IEnumerable)
        {
            foreach (var item in ((IEnumerable<IFileEntity>) propertyValue).OrderBy(entity => entity.Sort))
            {
                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
           Write(RenderScript(field, item));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                          
            }
        }
        else if (propertyValue != null)
        {
            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
       Write(RenderScript(field, (IFileEntity) propertyValue));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                             
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        ko.applyBindings(files[\"");

            
            #line 71 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                            Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("_array\"], $(\"#");

            
            #line 71 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
                                                                      Write(field.GetFullPropertyId());

            
            #line default
            #line hidden
WriteLiteral("-files-container\").get(0));\r\n\r\n    </script>\r\n");

            
            #line 74 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_File.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
