#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
    using CMS.PagesSettings.Forms;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ozi_Code.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ozi_Code_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ozi_Code_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
   
    var fieldSettings = (CodeSettings)WebContext.FieldSettings;
    var path = string.Format("{0}/{1}/{2}.js", "~/Areas/Admin/Scripts/Default/CodeMirror/mode", fieldSettings.Type, fieldSettings.Type);

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 250), Tuple.Create("\"", 330)
            
            #line 6 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 256), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Areas/Admin/Scripts/Default/CodeMirror/lib/codemirror.js")
            
            #line default
            #line hidden
, 256), false)
);

WriteLiteral("></script>\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 365), Tuple.Create("\"", 447)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 372), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Areas/Admin/Scripts/Default/CodeMirror/lib/codemirror.css")
            
            #line default
            #line hidden
, 372), false)
);

WriteLiteral(">\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 458), Tuple.Create("\"", 550)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 464), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Areas/Admin/Scripts/Default/CodeMirror/mode/javascript/javascript.js")
            
            #line default
            #line hidden
, 464), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 570), Tuple.Create("\"", 594)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 576), Tuple.Create<System.Object, System.Int32>(Url.Content(path)
            
            #line default
            #line hidden
, 576), false)
);

WriteLiteral("></script>\r\n<style>\r\n    .CodeMirror {\r\n        border-radius: 6px;\r\n    }\r\n</sty" +
"le>\r\n<textarea");

WriteAttribute("id", Tuple.Create(" id=\"", 690), Tuple.Create("\"", 733)
            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 695), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 695), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 734), Tuple.Create("\"", 779)
            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
, Tuple.Create(Tuple.Create("", 741), Tuple.Create<System.Object, System.Int32>(ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 741), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
                                                                                               Write(ViewData.TemplateInfo.FormattedModelValue);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    CodeMirror.fromTextArea(document.getElementById(\"");

            
            #line 17 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
                                                 Write(ViewData.TemplateInfo.HtmlFieldPrefix);

            
            #line default
            #line hidden
WriteLiteral("\"), {\r\n        value: \"");

            
            #line 18 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
            Write(ViewData.TemplateInfo.FormattedModelValue.ToString().Replace("\"", "\\\"").Replace("\n", "").Replace("\r", "\\\r"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n        mode: { name: \"");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ozi_Code.cshtml"
                   Write(fieldSettings.Type);

            
            #line default
            #line hidden
WriteLiteral("\", alignCDATA: true },\r\n        lineNumbers: true,\r\n        tabSize: 4,\r\n        " +
"matchBrakets: true\r\n    });\r\n\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
