#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ReferralExplains.cshtml"
    using DB.Entities;
    
    #line default
    #line hidden
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/ReferralExplains.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_ReferralExplains_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_ReferralExplains_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ReferralExplains.cshtml"
  
    var field = (ReferralField)System.Web.Configuration.WebContext.Model;
    var vm = new ReferralNameValueViewModel
        {
            Field = field,
        };

            
            #line default
            #line hidden
WriteLiteral(@"

<style>
    dl {}
    dt { float: left;font-weight: bold;font-family: monospace;padding-right: 15px;}
    dt:after { content: ' — ';}
    dd {}

    
/*refferal*/
#refferal { border:3px solid #f2f2f2; padding:10px; font-size:12px; }
#refferal * { font-family:Arial; }
#refferal div { margin:0 0 18px 0; }
#refferal div span { margin:0 10px; font-size:22px; }
#refferal .text, #refferal .text-box { border:1px solid #000; margin-left:10px; vertical-align:middle; width:300px; padding:4px 0; }
#refferal .chkbx { margin:0 10px 0 0; vertical-align:middle; }
#refferal .field { width:150px; display:inline-block; }
#refferal #tooths-c { border:1px solid #000; padding:3px 0; width:562px; margin:0 auto 22px auto; }
#refferal #tooths { border:0; margin:0 auto; }
#refferal #tooths td { width:50%; border:0; text-align:center; font-size:12px; padding:5px 2px; }
#refferal #tooths td input { vertical-align:middle; margin:0 1px 0 0; }
#refferal #tooths td label, #refferal #tooths td span { margin:0 4px 0 0; vertical-align:middle; font-size:14px; }
#refferal .d-item { background:#f2f2f2; padding:6px 10px; text-align:left; }
#refferal .d-item textarea { margin:0; padding:0; width:80%; height:100px; }
#refferal .serviceCalc {float: right;margin-top: -10%;}
	
</style>
<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1494), Tuple.Create("\"", 1542)
, Tuple.Create(Tuple.Create("", 1501), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/sh_style.css")
, 1501), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1572), Tuple.Create("\"", 1622)
, Tuple.Create(Tuple.Create("", 1578), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/sh_main.min.js")
, 1578), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1642), Tuple.Create("\"", 1692)
, Tuple.Create(Tuple.Create("", 1648), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/sh_html.min.js")
, 1648), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1712), Tuple.Create("\"", 1768)
, Tuple.Create(Tuple.Create("", 1718), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/sh_javascript.min.js")
, 1718), false)
);

WriteLiteral(@"></script>

<p>Если у данной услуги особый способ расчёта цены, необходимо написать функцию, которая будет возвращать значение по выбранным параметрам.</p>
<p>Метод будет вызываться при каждой итерации расчёта цены.</p>
<p>Можно использовать методы библиотеки jQuery.</p>
<p>Параметры, передаваемые в функцию:</p>

<dl>
    <dt>property</dt>
    <dd>
        Корневой элемент, свойство
    </dd>
</dl>
<dl>
    <dt>values</dt>
    <dd>Коллекция дочерних элементов, значения свойства</dd>
</dl>

<p>Конечная разметка для текущего поля выглядит так:</p>
<pre");

WriteLiteral(" class=\"sh_html sh_sourceCode\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\Admin\Views\Shared\EditorTemplates\ReferralExplains.cshtml"
                              Write(Html.Encode(Html.EditorFor(m => vm, string.Format("fields/{0}", field.Type))));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n\r\n<p>Пример для стандартного способа</p>\r\n<pre");

WriteLiteral(" class=\"sh_javascript sh_sourceCode\"");

WriteLiteral(@">    function(property, values) {
        if (!!property.data(""price"") && 
            ((values.length == 0 && property.is("":checked"")) || values.filter(':checked').length > 0)) { // Если для элемента указана цена, то возвращаем её
            return parseFloat(property.data(""price"").toString().replace("","", "".""));
        }
        // суммируем выделеные дочерние элементы
        var cp = values.filter(':checked').map(function() {
            var price = $(this).data(""price"");
            if (!price)
                return 0;
            return parseFloat(price.toString().replace("","", "".""));
        });
        return Math.sum(cp) || 0;
    };
</pre>

<script>
    $(function () {
        sh_highlightDocument();
    });
</script>");

        }
    }
}
#pragma warning restore 1591
