#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/SubscriptionGroup.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_SubscriptionGroup_cshtml_ : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_SubscriptionGroup_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
  
    IEnumerable<SubscriptionGroup> groups = WebContext.ViewBag.Groups;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
 foreach (var item in groups)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"subscription-group\"");

WriteLiteral(" data-id=\"");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
                                        Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
   Write(Lp.GetMessage(item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    .subscription-group { display: inline-block;padding: 10px;margin: 10px;border-radius: 4px;border: 1px dotted lightblue;}
    .subscription-group:hover { background: lightblue;cursor: pointer; }
    .subscription-group.active { background: lightsteelblue; }
    .subscription-group.active:hover { background: lightskyblue; }
</style>

<script>

    var groups = [];
");

            
            #line 22 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
     foreach (var item in groups)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("groups[");

            
            #line 24 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
             Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("] = [];\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
        foreach (var s in item.SubscribtionsTypes)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("groups[");

            
            #line 27 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
                 Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("].push(");

            
            #line 27 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
                                  Write(s.Id);

            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Shared\EditorTemplates\SubscriptionGroup.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral(@"
    var updateSubscriptions = function() {
        var active = [];
        $("".subscription-group.active"").each(function() {
            var id = $(this).data(""id"");
            active = active.concat(groups[id]);
        });
        $(""select[name=SubscribtionsTypes]"").val(active);
    };

    $(function() {
        $("".subscription-group"").on(""click"", function() {
            var $this = $(this);
            $this.toggleClass(""active"");
            updateSubscriptions();
        });
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
