#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
    using CMS;
    
    #line default
    #line hidden
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
    using DB;
    
    #line default
    #line hidden
    using DB.Entities;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
    using Libs;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_Main.cshtml")]
    public partial class _Areas_Admin_Views_Shared__Main_cshtml : CMS.Mvc.AdminViewPage<dynamic>
    {

#line 60 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
public System.Web.WebPages.HelperResult RenderModulesTree(IEnumerable<SitemapElement> modules)
                    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 60 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                

#line default
#line hidden

#line 61 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                     
                    foreach (var child in modules)
                    {
                        if (child.Childs.Count > 0)
                        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            <li><span");

WriteLiteralTo(__razor_helper_writer, " class=\"folder\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 66 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                       WriteTo(__razor_helper_writer, child.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n                                <ul>\r\n");

WriteLiteralTo(__razor_helper_writer, "                                    ");


#line 68 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
      WriteTo(__razor_helper_writer, RenderModulesTree(child.Childs));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n                                </ul>\r\n                            </li>\r\n");


#line 71 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                        }
                        else
                        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            <li><a ");


#line 74 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                                    if (child.Controller == (string)ViewContext.RouteData.Values["Controller"] && 
                                       (string.IsNullOrEmpty(child.Action) || child.Action == (string)ViewContext.RouteData.Values["action"])){

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");

WriteLiteralTo(__razor_helper_writer, "class=\"selected\"");

WriteLiteralTo(__razor_helper_writer, " ");


#line 75 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                                                                                                                                                                              }

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " href=\"");


#line 75 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                                                                                                                                                        WriteTo(__razor_helper_writer, Url.Action(child.Action, child.Controller));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\">");


#line 75 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                                                                                                                                                                                                     WriteTo(__razor_helper_writer, child.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></li>\r\n");


#line 76 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                        }
                    }
                

#line default
#line hidden
});

#line 78 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
}
#line default
#line hidden

        public _Areas_Admin_Views_Shared__Main_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <title>");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
      Write(WebContext.HtmlPageTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 126), Tuple.Create("\"", 220)
, Tuple.Create(Tuple.Create("", 133), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/development-bundle/themes/base/jquery.ui.a" +
"ll.css")
, 133), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 268), Tuple.Create("\"", 334)
, Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/jquery-ui-timepicker-addon.css")
, 275), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 366), Tuple.Create("\"", 431)
, Tuple.Create(Tuple.Create("", 373), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/fileuploader/fineuploader.css")
, 373), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 463), Tuple.Create("\"", 516)
, Tuple.Create(Tuple.Create("", 470), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/toastr/toastr.css")
, 470), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 548), Tuple.Create("\"", 612)
, Tuple.Create(Tuple.Create("", 555), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/toastr/toastr-responsive.css")
, 555), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 644), Tuple.Create("\"", 691)
, Tuple.Create(Tuple.Create("", 651), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Styles/Default/Default.css")
, 651), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 741), Tuple.Create("\"", 776)
, Tuple.Create(Tuple.Create("", 747), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-2.1.1.min.js")
, 747), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 823), Tuple.Create("\"", 922)
, Tuple.Create(Tuple.Create("", 829), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/development-bundle/ui/minified/jquery-ui.c" +
"ustom.min.js")
, 829), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 969), Tuple.Create("\"", 1067)
, Tuple.Create(Tuple.Create("", 975), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/development-bundle/ui/i18n/jquery.ui.datep" +
"icker-ru.js")
, 975), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1114), Tuple.Create("\"", 1183)
, Tuple.Create(Tuple.Create("", 1120), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/drag/jquery.dragsort-0.5.1.min.js")
, 1120), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1207), Tuple.Create("\"", 1263)
, Tuple.Create(Tuple.Create("", 1213), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/util.js")
, 1213), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1287), Tuple.Create("\"", 1345)
, Tuple.Create(Tuple.Create("", 1293), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/button.js")
, 1293), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1369), Tuple.Create("\"", 1427)
, Tuple.Create(Tuple.Create("", 1375), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/header.js")
, 1375), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1451), Tuple.Create("\"", 1509)
, Tuple.Create(Tuple.Create("", 1457), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/header.js")
, 1457), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1533), Tuple.Create("\"", 1597)
, Tuple.Create(Tuple.Create("", 1539), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/handler.base.js")
, 1539), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1621), Tuple.Create("\"", 1685)
, Tuple.Create(Tuple.Create("", 1627), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/handler.form.js")
, 1627), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1709), Tuple.Create("\"", 1772)
, Tuple.Create(Tuple.Create("", 1715), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/handler.xhr.js")
, 1715), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1796), Tuple.Create("\"", 1862)
, Tuple.Create(Tuple.Create("", 1802), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/uploader.basic.js")
, 1802), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1886), Tuple.Create("\"", 1941)
, Tuple.Create(Tuple.Create("", 1892), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/dnd.js")
, 1892), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1965), Tuple.Create("\"", 2025)
, Tuple.Create(Tuple.Create("", 1971), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/uploader.js")
, 1971), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2049), Tuple.Create("\"", 2114)
, Tuple.Create(Tuple.Create("", 2055), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/fileuploader/jquery-plugin.js")
, 2055), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2138), Tuple.Create("\"", 2211)
, Tuple.Create(Tuple.Create("", 2144), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/js/jquery-ui-sliderAccess.js")
, 2144), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2235), Tuple.Create("\"", 2312)
, Tuple.Create(Tuple.Create("", 2241), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/js/jquery-ui-timepicker-addon.js")
, 2241), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2336), Tuple.Create("\"", 2403)
, Tuple.Create(Tuple.Create("", 2342), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/js/ui.datepicker-ru.js")
, 2342), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2427), Tuple.Create("\"", 2501)
, Tuple.Create(Tuple.Create("", 2433), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/jqueryUI/js/jquery-ui-timepicker-ru.js")
, 2433), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2525), Tuple.Create("\"", 2587)
, Tuple.Create(Tuple.Create("", 2531), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/knockout/knockout-2.2.1.js")
, 2531), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2611), Tuple.Create("\"", 2676)
, Tuple.Create(Tuple.Create("", 2617), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/knockout/knockout-sortable.js")
, 2617), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2700), Tuple.Create("\"", 2752)
, Tuple.Create(Tuple.Create("", 2706), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/toastr/toastr.js")
, 2706), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2776), Tuple.Create("\"", 2826)
, Tuple.Create(Tuple.Create("", 2782), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/autoNumeric.js")
, 2782), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2850), Tuple.Create("\"", 2896)
, Tuple.Create(Tuple.Create("", 2856), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/Default.js")
, 2856), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2943), Tuple.Create("\"", 2988)
, Tuple.Create(Tuple.Create("", 2949), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/Mktree.js")
, 2949), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\t<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3032), Tuple.Create("\"", 3072)
, Tuple.Create(Tuple.Create("", 3038), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Ckeditor/ckeditor.js")
, 3038), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\t<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3116), Tuple.Create("\"", 3165)
, Tuple.Create(Tuple.Create("", 3122), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/Myckconfig.js")
, 3122), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3212), Tuple.Create("\"", 3262)
, Tuple.Create(Tuple.Create("", 3218), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/Scripts/Default/files-logic.js")
, 3218), false)
);

WriteLiteral("></script>\r\n</head>\r\n\r\n<body>\r\n\r\n    <table");

WriteLiteral(" id=\"logo-table\"");

WriteLiteral(">\r\n        <tr>\r\n            <td");

WriteLiteral(" id=\"logo-left\"");

WriteLiteral("><div");

WriteLiteral(" id=\"logo\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3389), Tuple.Create("\"", 3448)
            
            #line 49 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
, Tuple.Create(Tuple.Create("", 3395), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Areas/Admin/Images/Default/logo.gif")
            
            #line default
            #line hidden
, 3395), false)
);

WriteLiteral(" alt=\"OziCms.cms 4.0\"");

WriteLiteral(" /><div");

WriteLiteral(" id=\"ozi-version\"");

WriteLiteral(">Версия — 4.0</div></div></td>\r\n            <td");

WriteLiteral(" id=\"logo-right\"");

WriteLiteral("><span");

WriteLiteral(" id=\"hello\"");

WriteLiteral(">Здравствуйте, ");

            
            #line 50 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
                                                          Write(Request.ServerVariables["AUTH_USER"]);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" href=\"/account/logout\"");

WriteLiteral(">Выйти</a></span></td>\r\n        </tr>\r\n    </table>\r\n\r\n    <table");

WriteLiteral(" id=\"main-table\"");

WriteLiteral(">\r\n        <tr>\r\n            <td");

WriteLiteral(" id=\"main-left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"root\"");

WriteLiteral(">Konig Labs</div>\r\n                \r\n                \r\n");

WriteLiteral("                \r\n                <ul");

WriteLiteral(" class=\"mktree\"");

WriteLiteral(" id=\"modules-ul\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
               Write(RenderModulesTree(new Sitemap(@Url.Content("~/Modules.sitemap")).SitemapList));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </ul>\r\n                \r\n                <div");

WriteLiteral(" id=\"left-menu\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Функции</div>\r\n                    <div");

WriteLiteral(" class=\"left-function\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create("  href=\"", 5270), Tuple.Create("\"", 5330)
            
            #line 86 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
, Tuple.Create(Tuple.Create("", 5278), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Admin.Utils.ClearApplicationCache())
            
            #line default
            #line hidden
, 5278), false)
);

WriteLiteral(">Очистить кэш</a></div>\r\n                    <div");

WriteLiteral(" class=\"left-function\"");

WriteLiteral("><a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">На главную</a></div>\r\n                </div>\r\n                \r\n            </td" +
">\r\n            \r\n            <td");

WriteLiteral(" id=\"main-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\_Main.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
