#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/Create.cshtml")]
    public partial class _Areas_Admin_Views_Shared_Create_cshtml : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
  
    WebContext.HtmlPageTitle = "Ozi.cms — создание объекта";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
 using (Html.BeginForm("Create", Request.RequestContext.RouteData.Values["controller"].ToString(), FormMethod.Post, new { enctype = "multipart/form-data", id = "edit-form" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"form-table\"");

WriteLiteral(">\r\n        <tr><th>Новый объект</th></tr>\r\n    </table>\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"returnUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 402), Tuple.Create("\"", 431)
            
            #line 12 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
, Tuple.Create(Tuple.Create("", 410), Tuple.Create<System.Object, System.Int32>(WebContext.ReturnUrl
            
            #line default
            #line hidden
, 410), false)
);

WriteLiteral("/>\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\Create.cshtml"

    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
                                 
        
    Html.RenderPartial(Url.Content("~/Areas/Admin/Views/Shared/Form/FormButtons.cshtml"));
    
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
Write(Html.EditorFor(model => model, "ozi_Object"));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Shared\Create.cshtml"
                                                 
    
    Html.RenderPartial(Url.Content("~/Areas/Admin/Views/Shared/Form/FormButtons.cshtml"));
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
