#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Shared_Edit_cshtml : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
  
    WebContext.HtmlPageTitle = "Ozi.cms — редактирование объекта";
    Layout = MVC.Admin.Shared.Views._Main;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var _editFormId = \"edit-form\";\r\n</script>\r\n\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
 using (Html.BeginForm(Constants.EditView, Request.RequestContext.RouteData.Values["controller"].ToString(), FormMethod.Post, new { enctype = "multipart/form-data", id = "edit-form" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"returnUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 470), Tuple.Create("\"", 499)
            
            #line 14 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 478), Tuple.Create<System.Object, System.Int32>(WebContext.ReturnUrl
            
            #line default
            #line hidden
, 478), false)
);

WriteLiteral("/>\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
Write(Html.Hidden("Id"));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"form-table\"");

WriteLiteral(">\r\n        <tr>\r\n            <th>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                 if (WebContext.PrevId.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" style=\"float:left;\"");

WriteLiteral("> &larr; ");

            
            #line 21 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                                                 Write(Html.ActionLink("Предыдущий элемент", Actions.Edit, new { id = WebContext.PrevId.Value}));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 23 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
           Write(Html.Raw(Model.ToString()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                 if (WebContext.NextId.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" style=\"float:right;\"");

WriteLiteral(">");

            
            #line 26 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                                          Write(Html.ActionLink("Следующий элемент", Actions.Edit, new { id = WebContext.NextId.Value}));

            
            #line default
            #line hidden
WriteLiteral(" &rarr; </span>\r\n");

            
            #line 27 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </th>\r\n        </tr>\r\n\r\n    </table>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"

    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                                 
        
	Html.RenderPartial(Url.Content("~/Areas/Admin/Views/Shared/Form/FormButtons.cshtml"));
    
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
Write(Html.EditorFor(model => model, "ozi_Object"));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\Shared\Edit.cshtml"
                                                 
    
	Html.RenderPartial(Url.Content("~/Areas/Admin/Views/Shared/Form/FormButtons.cshtml"));
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
