#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\GlobalActions\Create.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/GlobalActions/Create.cshtml")]
    public partial class _Areas_Admin_Views_Shared_GlobalActions_Create_cshtml : CMS.Mvc.AdminViewPage<ListViewModel>
    {
        public _Areas_Admin_Views_Shared_GlobalActions_Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteLiteral(" class=\"global-action create\"");

WriteAttribute("href", Tuple.Create(" href=\"", 71), Tuple.Create("\"", 111)
            
            #line 3 "..\..\Areas\Admin\Views\Shared\GlobalActions\Create.cshtml"
, Tuple.Create(Tuple.Create("", 78), Tuple.Create<System.Object, System.Int32>(Url.Action(Constants.CreateView)
            
            #line default
            #line hidden
, 78), false)
);

WriteLiteral(">Добавить объект</a>");

        }
    }
}
#pragma warning restore 1591
