#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/ListActions/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Shared_ListActions_Edit_cshtml : CMS.Mvc.AdminViewPage<DB.Entities.IEntity>
    {
        public _Areas_Admin_Views_Shared_ListActions_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteLiteral(" class=\"list-action\"");

WriteAttribute("href", Tuple.Create(" href=\"", 52), Tuple.Create("\"", 113)
            
            #line 3 "..\..\Areas\Admin\Views\Shared\ListActions\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 59), Tuple.Create<System.Object, System.Int32>(Url.Action(Constants.EditView, new { id = Model.Id })
            
            #line default
            #line hidden
, 59), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 119), Tuple.Create("\"", 205)
            
            #line 3 "..\..\Areas\Admin\Views\Shared\ListActions\Edit.cshtml"
                 , Tuple.Create(Tuple.Create("", 125), Tuple.Create<System.Object, System.Int32>( CMS.PagesSettings.Settings.MediaRoot +"/Areas/Admin/Images/Default/edit.png"
            
            #line default
            #line hidden
, 125), false)
);

WriteLiteral(" alt=\"Редактировать\"");

WriteLiteral(" /></a>");

        }
    }
}
#pragma warning restore 1591
