#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
    using DB.Entities;
    
    #line default
    #line hidden
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/ListActions/Visibility.cshtml")]
    public partial class _Areas_Admin_Views_Shared_ListActions_Visibility_cshtml : CMS.Mvc.AdminViewPage<DB.Entities.IEntity>
    {
        public _Areas_Admin_Views_Shared_ListActions_Visibility_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
 if (((IVisibleEntity)Model).Visibility)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"list-action\"");

WriteAttribute("href", Tuple.Create(" href=\"", 121), Tuple.Create("\"", 217)
            
            #line 6 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
, Tuple.Create(Tuple.Create("", 128), Tuple.Create<System.Object, System.Int32>(Url.Action(Constants.SetVisibilityAction, new {id = Model.Id, visibilityToSet = false })
            
            #line default
            #line hidden
, 128), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 223), Tuple.Create("\"", 316)
            
            #line 6 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 229), Tuple.Create<System.Object, System.Int32>(CMS.PagesSettings.Settings.MediaRoot +"/Areas/Admin/Images/Default/VisibilityOn.png"
            
            #line default
            #line hidden
, 229), false)
);

WriteLiteral(" alt=\"Выключить\"");

WriteLiteral(" /></a>\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"list-action\"");

WriteAttribute("href", Tuple.Create(" href=\"", 380), Tuple.Create("\"", 476)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Url.Action(Constants.SetVisibilityAction, new { id = Model.Id, visibilityToSet = true })
            
            #line default
            #line hidden
, 387), false)
);

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 488), Tuple.Create("\"", 582)
            
            #line 11 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(CMS.PagesSettings.Settings.MediaRoot +"/Areas/Admin/Images/Default/VisibilityOff.png"
            
            #line default
            #line hidden
, 494), false)
);

WriteLiteral(" alt=\"Включить\"");

WriteLiteral(" /></a>\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\ListActions\Visibility.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
