#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
    using CMS.PagesSettings;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
    using Libs;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/DisplayTemplates/ozi_Filter.cshtml")]
    public partial class _Areas_Admin_Views_Shared_DisplayTemplates_ozi_Filter_cshtml_ : CMS.Mvc.AdminViewPage<string>
    {
        public _Areas_Admin_Views_Shared_DisplayTemplates_ozi_Filter_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
  
	var column = (FilterSettings)ViewData["ColSettings"];
	var settings = (Settings)ViewData["Settings"];
	var curval = Request[column.FilterField];
	var formName = "form" + column.FilterField;

            
            #line default
            #line hidden
WriteLiteral("\r\n\t<select");

WriteLiteral(" class=\"get-change filter-select\"");

WriteAttribute("name", Tuple.Create(" name=\"", 297), Tuple.Create("\"", 323)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
, Tuple.Create(Tuple.Create("", 304), Tuple.Create<System.Object, System.Int32>(column.FilterField
            
            #line default
            #line hidden
, 304), false)
);

WriteLiteral(">\r\n\t\t<option");

WriteAttribute("value", Tuple.Create(" value=\"", 336), Tuple.Create("\"", 357)
            
            #line 11 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
, Tuple.Create(Tuple.Create("", 344), Tuple.Create<System.Object, System.Int32>(string.Empty
            
            #line default
            #line hidden
, 344), false)
);

WriteLiteral(">");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
                            Write(column.Title ?? column.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
		
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
   foreach (var item in column.FilterValues.Where(entity => entity != null).OrderBy(entity => entity.ToString()))
  {
	  var val = TypeHelpers.GetPropertyValue(item, "Id").ToString();

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<option");

WriteAttribute("value", Tuple.Create(" value=\"", 597), Tuple.Create("\"", 609)
            
            #line 15 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
, Tuple.Create(Tuple.Create("", 605), Tuple.Create<System.Object, System.Int32>(val
            
            #line default
            #line hidden
, 605), false)
);

            
            #line 15 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
                  Write(Html.Raw(val == curval ? " selected='selected'" : string.Empty));

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
                                                                                   Write(item.ToString());

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\DisplayTemplates\ozi_Filter.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("\t</select>\r\n");

        }
    }
}
#pragma warning restore 1591
