#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
    using CMS.PagesSettings.Forms;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/Collections/ozi_File.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_File_cshtml : CMS.Mvc.AdminViewPage<UploadFileSettings>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_File_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
  
    var bind = string.Format("{{visible: show{0}panel, attr: {{ id: generateId() + '_{0}', 'data-parentid': ItemId, 'data-modelid': ModelId }}}}", Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div>\r\n    <img");

WriteLiteral(" data-bind=\"{visible: show");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                              Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("img, attr: { src: ");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                                                             Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(", width: \'");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                                                                                    Write(Model.Size);

            
            #line default
            #line hidden
WriteLiteral("\' }}\"");

WriteLiteral("/>\r\n    <span");

WriteLiteral(" data-bind=\"{visible: show");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                               Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("text, text: \'Для начала сохраните объект\' }\"");

WriteLiteral("></span>\r\n    <div");

WriteLiteral(" data-url=\"");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
              Write(Url.Action(Actions.UploadFileCollectionItem));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-path=\"");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                                                                        Write(Model.GetFullPropertyName());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-bind=\"");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_File.cshtml"
                                                                                                                 Write(Html.Raw(bind));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
