#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
    using CMS.PagesSettings.Forms;
    
    #line default
    #line hidden
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/Collections/ozi_Select.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_Select_cshtml : CMS.Mvc.AdminViewPage<SelectSettings>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_Select_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
 if (!Model.Editable)
{
    var b = string.Format("{{value: {0}, options: available{0}, optionsText: 'label', optionsValue: 'value', attr: {{ name: generateName() + '.{0}' }}}}", Model.Name);

            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteLiteral(" data-bind=\"");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
                  Write(Html.Raw(b));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></select>\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
}
else
{
    var b = string.Format("{{value: current{1}, attr: {{ id: generateId() + '_{0}', name: generateName() + '.{2}.{0}', 'data-hiddenid': generateId() + '_{3}' }}}}", Model.OptionTitle, Model.Name, Model.Reference, Model.OptionValue);

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" data-bind=\"");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
                               Write(Html.Raw(string.Format("{{value: {1}, attr: {{id: generateId()  + '_{0}', name: generateName() + '.{2}.{0}'}}}}", Model.OptionValue, Model.Name, Model.Reference)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n");

WriteLiteral("    <input");

WriteLiteral(" class=\"autocomplete ozi-string\"");

WriteLiteral(" data-sourcename=\"");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
                                                        Write(Model.GetFullPropertyName().Replace(".", "_"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
                                                                                                                                Write(Html.Raw(b));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_Select.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
