#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_String.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/Collections/ozi_String.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_String_cshtml : CMS.Mvc.AdminViewPage<CMS.PagesSettings.Forms.StringSettings>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_Collections_ozi_String_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_String.cshtml"
  
    var bind = string.Format("{{value: {0}, attr: {{ name: generateName() + '.{0}' }}}}", Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"ozi-string\"");

WriteLiteral(" data-bind=\"");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Collections\ozi_String.cshtml"
                                            Write(Html.Raw(bind));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n");

        }
    }
}
#pragma warning restore 1591
