#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    
    #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
    using Libs;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/Shared/ObjectFields.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_Shared_ObjectFields_cshtml : CMS.Mvc.AdminViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_Shared_ObjectFields_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
  
    var settings = WebContext.CurrentTab;
    var roles = Roles.GetRolesForUser(User.Identity.Name);
    Func<string, bool> allowed = role => string.IsNullOrEmpty(role) || roles.Contains(role);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
 foreach (var field in settings.Fields.Where(field => allowed(field.RoleName)))
{
    WebContext.FieldSettings = field;
    if (field.Control == "hidden")
    {
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
   Write(Html.Editor(field.Name, field.Control, field.Name, new { FieldSettings = field }));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                                                                                          
    }
    else if (string.IsNullOrEmpty(field.Condition) || (bool)TypeHelpers.GetPropertyValue(Model, field.Condition))
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr");

WriteLiteral(" class=\"form-table-row\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
             if (field.Control == "hr")
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                    <hr />\r\n                </td>\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
               Write(field.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"form-table-data\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
               Write(Html.Editor(field.Name, field.Control, field.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                     if (field.Info != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"field-info\"");

WriteLiteral(">");

            
            #line 35 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                                           Write(field.Info);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"error-message\"");

WriteLiteral(">");

            
            #line 37 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
                                          Write(Html.ValidationMessage(field.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </td>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Shared\ObjectFields.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
