// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace KonigLabs.Controllers
{
    public partial class PolicyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PolicyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PolicyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PolicyController Actions { get { return MVC.Policy; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Policy";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Policy";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PrivatePolicyAgreement = "PrivatePolicyAgreement";
            public readonly string PersonalDataAgreement = "PersonalDataAgreement";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PrivatePolicyAgreement = "PrivatePolicyAgreement";
            public const string PersonalDataAgreement = "PersonalDataAgreement";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string PersonalDataAgreement_en = "PersonalDataAgreement_en";
                public readonly string PersonalDataAgreement_ru = "PersonalDataAgreement_ru";
                public readonly string PrivatePolicyAgreement_en = "PrivatePolicyAgreement_en";
                public readonly string PrivatePolicyAgreement_ru = "PrivatePolicyAgreement_ru";
            }
            public readonly string PersonalDataAgreement_en = "~/Views/Policy/PersonalDataAgreement_en.cshtml";
            public readonly string PersonalDataAgreement_ru = "~/Views/Policy/PersonalDataAgreement_ru.cshtml";
            public readonly string PrivatePolicyAgreement_en = "~/Views/Policy/PrivatePolicyAgreement_en.cshtml";
            public readonly string PrivatePolicyAgreement_ru = "~/Views/Policy/PrivatePolicyAgreement_ru.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PolicyController : KonigLabs.Controllers.PolicyController
    {
        public T4MVC_PolicyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PrivatePolicyAgreementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrivatePolicyAgreement()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrivatePolicyAgreement);
            PrivatePolicyAgreementOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PersonalDataAgreementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PersonalDataAgreement()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PersonalDataAgreement);
            PersonalDataAgreementOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
