#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
    using System.Net.Mail;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    #line 3 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
    using CMS;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteSettings/Emails.cshtml")]
    public partial class _Areas_Admin_Views_SiteSettings_Emails_cshtml : CMS.Mvc.AdminViewPage<System.Net.Configuration.SmtpSection>
    {
        public _Areas_Admin_Views_SiteSettings_Emails_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
  
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
 using (Html.BeginForm(MVC.Admin.SiteSettings.Emails()))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-save-buttons\"");

WriteLiteral("><input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"save-button\"");

WriteLiteral(" value=\"Сохранить\"");

WriteLiteral("></div>\r\n");

WriteLiteral("    <h2>Настройки почты</h2>\r\n");

WriteLiteral("    <fieldset>\r\n        <legend></legend>\r\n        <input ");

            
            #line 16 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
          Write(ByCondition(Model.DeliveryMethod == SmtpDeliveryMethod.SpecifiedPickupDirectory, "checked"));

            
            #line default
            #line hidden
WriteLiteral(" type=\"radio\" name=\"DeliveryMethod\" id=\"DeliveryMethod_SpecifiedPickupDirectory\" " +
"data-target=\"SpecifiedPickupDirectory\" value=\"SpecifiedPickupDirectory\" />\r\n    " +
"    <label");

WriteLiteral(" for=\"DeliveryMethod_SpecifiedPickupDirectory\"");

WriteLiteral(">Складывать письма в папку</label>\r\n        <fieldset");

WriteLiteral(" id=\"SpecifiedPickupDirectory\"");

WriteLiteral(" class=\"mailsettings\"");

WriteLiteral(" ");

            
            #line 18 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                                                                Write(ByCondition(Model.DeliveryMethod != SmtpDeliveryMethod.SpecifiedPickupDirectory, "disabled"));

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <legend></legend>\r\n            <label");

WriteLiteral(" for=\"folder\"");

WriteLiteral(">Путь к отправленным письмам</label>");

            
            #line 20 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                                                              Write(Html.EditorFor(model => model.SpecifiedPickupDirectory.PickupDirectoryLocation));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </fieldset>\r\n    </fieldset>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend></legend>\r\n        <input ");

            
            #line 26 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
          Write(ByCondition(Model.DeliveryMethod == SmtpDeliveryMethod.Network, "checked"));

            
            #line default
            #line hidden
WriteLiteral(" type=\"radio\" name=\"DeliveryMethod\" id=\"DeliveryMethod_Network\" data-target=\"Netw" +
"ork\" value=\"Network\" />\r\n        <label");

WriteLiteral(" for=\"DeliveryMethod_Network\"");

WriteLiteral(">Отправка по сети</label>\r\n        <fieldset");

WriteLiteral(" id=\"Network\"");

WriteLiteral(" class=\"mailsettings\"");

WriteLiteral(" ");

            
            #line 28 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                                               Write(ByCondition(Model.DeliveryMethod != SmtpDeliveryMethod.Network, "disabled"));

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <legend></legend>\r\n            <table>\r\n                <tr>\r\n    " +
"                <td>");

            
            #line 32 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.ClientDomain));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 33 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.ClientDomain));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 36 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.DefaultCredentials));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 37 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.DefaultCredentials));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 40 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.EnableSsl));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 41 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.EnableSsl));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 44 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.Host));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 45 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.Host));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 48 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.Port));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 49 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.Port));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 52 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.UserName));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 53 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.UserName));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 56 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.LabelFor(model => model.Network.Password));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 57 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
                   Write(Html.EditorFor(model => model.Network.Password));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n            </table>\r\n        </fieldset>\r\n    </fi" +
"eldset>\r\n");

            
            #line 62 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-save-buttons\"");

WriteLiteral("><input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"save-button\"");

WriteLiteral(" value=\"Сохранить\"");

WriteLiteral("></div>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\SiteSettings\Emails.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    $(\"input[name=DeliveryMethod]\").click(function () {\r\n        $(\"." +
"mailsettings\").attr(\"disabled\", \"disabled\");\r\n        $(\"#\" + $(this).data(\"targ" +
"et\")).removeAttr(\"disabled\");\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
