#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CMS.Mvc;
    using CMS.PagesSettings.Lists;
    using CMS.ViewModels;
    using DB.Entities;
    using Libs;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteSettings/Logs.cshtml")]
    public partial class _Areas_Admin_Views_SiteSettings_Logs_cshtml : CMS.Mvc.AdminViewPage<List<DB.Entities.EmailLog>>
    {
        public _Areas_Admin_Views_SiteSettings_Logs_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
  
    var index = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
 if (Model.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <style>\r\n        tr.error, tr.error td.form-table-label { background: lightpi" +
"nk; }\r\n        .hidden { display: none; }\r\n    </style>\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"form-table\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
         foreach (var item in Model)
        {
            index++;

            
            #line default
            #line hidden
WriteLiteral("            <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 346), Tuple.Create("\"", 404)
, Tuple.Create(Tuple.Create("", 354), Tuple.Create("form-table-row", 354), true)
            
            #line 18 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
, Tuple.Create(Tuple.Create(" ", 368), Tuple.Create<System.Object, System.Int32>(ByCondition(!item.Status, "error")
            
            #line default
            #line hidden
, 369), false)
);

WriteLiteral(">\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                        Write(index);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral("><label>");

            
            #line 20 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                               Write(item.Date);

            
            #line default
            #line hidden
WriteLiteral("</label></td>\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral("><label>");

            
            #line 21 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                               Write(item.From);

            
            #line default
            #line hidden
WriteLiteral("</label></td>\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral("><label>");

            
            #line 22 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                               Write(item.To);

            
            #line default
            #line hidden
WriteLiteral("</label></td>\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral("><label>");

            
            #line 23 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                               Write(item.Subject);

            
            #line default
            #line hidden
WriteLiteral("</label></td>\r\n                <td");

WriteLiteral(" class=\"form-table-label\"");

WriteLiteral("><a");

WriteLiteral(" class=\"expander\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("target-id", Tuple.Create(" target-id=\"", 865), Tuple.Create("\"", 895)
, Tuple.Create(Tuple.Create("", 877), Tuple.Create("row-details-", 877), true)
            
            #line 24 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                   , Tuple.Create(Tuple.Create("", 889), Tuple.Create<System.Object, System.Int32>(index
            
            #line default
            #line hidden
, 889), false)
);

WriteLiteral(">Детали</a></td>\r\n            </tr>\r\n");

WriteLiteral("            <tr");

WriteLiteral(" class=\"form-table-row hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 978), Tuple.Create("\"", 1001)
, Tuple.Create(Tuple.Create("", 983), Tuple.Create("row-details-", 983), true)
            
            #line 26 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
, Tuple.Create(Tuple.Create("", 995), Tuple.Create<System.Object, System.Int32>(index
            
            #line default
            #line hidden
, 995), false)
);

WriteLiteral(">\r\n                <td>&nbsp;</td>\r\n                <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                    <p>Тема письма: ");

            
            #line 29 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                               Write(item.Subject);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <p>Содержимое</p>\r\n                    <p>");

            
            #line 31 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                  Write(item.Content);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n            </tr>\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
            if (!item.Status)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                        <p>Тип ошибки: ");

            
            #line 38 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                  Write(item.Type);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        <p>Сообщение: ");

            
            #line 39 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                                 Write(item.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        <p>Стек</p>\r\n                        <p>");

            
            #line 41 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
                      Write(item.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n");

            
            #line 47 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        $(function() {\r\n            $(\".expander\").click(function()" +
" {\r\n                var id = $(this).attr(\"target-id\");\r\n                $(\"#\" +" +
" id).toggle();\r\n            });\r\n        });\r\n    </script>\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p>В логах нет записей</p>\r\n");

            
            #line 60 "..\..\Areas\Admin\Views\SiteSettings\Logs.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
