// <auto-generated />
namespace KonigLabs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201503270842523_FixCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
