// <auto-generated />
namespace KonigLabs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Article : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Article));
        
        string IMigrationMetadata.Id
        {
            get { return "201503271656437_Article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
